- version: 1
  name: Product Added
  description: User adds a product to their shopping cart.
  metadata:
    code_owner: Maura
    product_owner: Greg
  properties:
    - name: box_size
      description: The size of the box (e.g. 12, 24, 36 patties)
      type: number
      allow_null: true
    - name: cart_id
      description: Cart ID to which the product was added to
      type: string
      required: true
    - name: name
      description: Name of the product being viewed
      type: string
      required: true
    - name: price
      description: Price ($) of the product being viewed
      type: number
      required: true
    - name: product_id
      description: Database id of the product being viewed
      type: number
      required: true
    - name: quantity
      description: Quantity of the product
      type: number
      required: true
    - name: variant
      description: Variant of the product (e.g. mild, medium, spicy)
      type: string
      required: true
      enum:
        - mild
        - medium
        - spicy
