name: QA CI Suite - Reflekt <-> Segment
on:
  pull_request:
    branches:
      - main

jobs:
  test-and-sync-plan-changes-qa:
    name: Test and Sync Tracking Plan Changes to QA
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.9']
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Get entire history

      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python: ${{ matrix.python-version }}

      - name: Install Reflekt
        run: |
          pip install reflekt

      - name: CI Setup - make reflekt_config.yml for CI suite
        run: |
          mkdir /home/runner/.reflekt
          echo "${{ secrets.CI_REFLEKT_CONFIG_YML }}" > /home/runner/.reflekt/reflekt_config.yml
          sleep 5

      - name: CI Setup - set config_path in reflekt_project.yml
        uses: jacobtomlinson/gha-find-replace@2.0.0
        with:
          find: "# config_path: /absolute/path/to/reflekt_config.yml"
          replace: "config_path: /home/runner/.reflekt/reflekt_config.yml"
          include: "reflekt_project.yml"  # Only search this file

      - name: 'QA CI Suite: Reflekt <-> Segment Protocols'
        run: |
          ./ci_reflekt_segment_qa.sh
